### ISSUE TITLE
Production of MC4-Plus rev.2

### ISSUE THREAD

**Issue by IvolgaDmitriy** [icub-tech-iit/electronics-boards-public#3]
Our team want to creating project with using the motor driver board MC4-Plus (rev.2). We ran into problem at stage of negotiations with companies:

"For layer 4 and 5, all gaps must be at least 0.35 mm. For the remaining layers, the gaps must be at least 0.15 mm. At the moment, the project is designed only for 18mkm of foil."

Files was used from "electronics-boards-public/motor-control/mc4-plus/output/Gerber/REV2/". Can do you prompt companies for creating this pcb?

**Comment by maggia80** [comment]
Hi @IvolgaDmitriy,

the layup of the board is quite special since the inner layers have a ticker copper plane, but we didn't get any issue in finding providers of such a PCB. However, we are used to asking the supplier of the assembly to search for a PCB producer. Therefore we don't know the name of the producers of the PCB.

**Comment by IvolgaDmitriy** [comment]
Hello maggia80,
Could you give name of company or their contact information so that we can order manufacturing PCB?

**Comment by maggia80** [comment]
this is one:  http://www.neohm.it/

**Comment by IvolgaDmitriy** [comment]
Thank you for answer.

**Comment by maggia80** [comment]
let me close the issue
